# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

#install! 'cocoapods',
#         :preserve_pod_file_structure => true

install! 'cocoapods',
         :preserve_pod_file_structure => true,
         :deterministic_uuids => false


workspace 'BPComponents_ocDemo.xcworkspace'

target 'BPComponents_ocDemo' do
  project 'BPComponents_ocDemo.project'
  pod 'Masonry', '~> 1.1.0'

pod 'BPComponents_oc', :path => '../'
end

target 'BPComponents_oc' do
  project '../BPComponents_oc/BPComponents_oc.project'
end
